name: backup
description: Cli script to create backup files from docker containers, handles them afterwards with restic
version: 0.0.2
author: Markus Krebs <markuskrebs93@gmail.com>
homepage: https://www.jayjah.eu
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies
dependencies:
  # store local data
  # Apache 2 License
  # https://pub.dev/packages/hive
  hive: ^2.0.0

  # cli-tools
  # MIT-License
  # https://pub.dev/packages/dcli
  dcli: ^0.50.2

  # to compress data
  # Apache 2 License
  # https://pub.dev/packages/dcli
  archive: ^3.1.2

  # mailjet client
  # MIT-License
  mailjet_sender:
    git:
      url: https://github.com/jayjah/mailjet_sender.git
      ref: master

dev_dependencies:
  test: ^1.16.5

  # analyzer rules
  pedantic: ^1.11.0

  # build gen tools
  #hive_generator: ^1.0.0
  #build_runner: ^1.11.5

# dart script
executables:
  backup: main